---
- name: Get join command from master
  hosts: Master
  become: true
  tasks:
    - name: Get kubeadm join command
      command: kubeadm token create --print-join-command
      register: join_command

- name: Join worker nodes to the cluster
  hosts: Worker
  become: true
  tasks:
    - name: Execute join command
      command: "{{ hostvars[groups['Master'][0]].join_command.stdout }} --cri-socket /var/run/cri-dockerd.sock  --ignore-preflight-errors=NumCPU,Mem"

    - name: Label the node
      command: kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/worker=worker
      delegate_to: Master