#cloud-config

package_update: true
package_upgrade: true

groups:
  - docker

system_info:
  default_user:
    groups: [ docker ]

users:
  - default
  - name: michaelbeutler
    gecos: Michael Beutler
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_import_id:
      - gh:michaelbeutler
    lock_passwd: true
    passwd: $y$j9T$v.wvgArbXq0Y0vEYvkGbI/$Ecy9APcZGb8qqWw6QLxNq9UfQ6eoUk7g9vL8ihLRJID
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPPtp/ITTwdWkK6OK5TdvWODKuhq8kJAw3eSIIctMY7r michael.beutler@students.fhnw.ch
  - name: eval
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAGd1sEHWR+J1kz4TokLXzpTFGFO8dX3T1zWjQ0rJqsnrx1m8nTotpWTuqgQCgtIzQ8Usvy4wK3/pRV1raFtYThvEgHleB85YOaSiFEYs1rUz6KkQ8lhKuSXYLp8YnJtv0MCJNfm8jY816RvOqa+v7mS/+67ly4PXwf1jfibzw1bSZHc4w== snorwin@nano-x1
    lock_passwd: true

packages:
  - ssh-import-id
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - unattended-upgrades
  - git

runcmd:
  - curl -fsSL https://gvisor.dev/archive.key | sudo gpg --dearmor -o /usr/share/keyrings/gvisor-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/gvisor-archive-keyring.gpg] https://storage.googleapis.com/gvisor/releases release main" | sudo tee /etc/apt/sources.list.d/gvisor.list > /dev/null
  - sudo apt-get update && sudo apt-get install -y runsc
  # - ssh-import-id gh:michaelbeutler
  # - for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do sudo apt-get remove $pkg; done
  # - install -m 0755 -d /etc/apt/keyrings
  # - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  # - chmod a+r /etc/apt/keyrings/docker.asc
  # - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  # - apt-get update
  # - apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
  # - usermod -aG docker michaelbeutler
  # - usermod -aG docker eval

  # # Create a new containerd namespace
  # - ctr namespace create cloud-fs25
  # # Pull the nginx:latest image into the cloud-fs25 namespace
  # - ctr --namespace cloud-fs25 images pull docker.io/library/nginx:latest
  # # Create a container named nginx_cloud_fs25 from the nginx:latest image
  # - ctr --namespace cloud-fs25 run -d --rm --tty docker.io/library/nginx:latest nginx_cloud_fs25

  # - git clone git@gitlab.fhnw.ch:dps/module/cloud/monitoringstack.git

final_message: "The system is finally up, after $UPTIME seconds"